spring:
  application:
    name: API
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false
  profiles:
    active: local
  docker:
    compose:
      file: ./compose.yaml

# Common configuration for all profiles
logging:
  level:
    org:
      flywaydb: DEBUG
