spring:
  application:
    name: API
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/V1__create_initial_schema.sql,classpath:db/migration/V2__fix_schema_and_insert_data.sql
logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        jdbc: DEBUG
