spring:
  application:
    name: API
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/V1__create_initial_schema.sql,classpath:db/migration/V2__fix_schema_and_insert_data.sql
logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        jdbc: DEBUG
