spring:
  application:
    name: API
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  profiles:
    active: local
  docker:
    compose:
      file: ./api/compose.yaml

# Common configuration for all profiles
logging:
  level:
    org:
      flywaydb: DEBUG
