-- Create tenants table
CREATE TABLE tenants (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(2000)
);

-- Insert default tenant
INSERT INTO tenants (name, description) VALUES ('default', 'Default tenant');

-- Add tenant_id column to all existing tables
ALTER TABLE races ADD COLUMN tenant_id BIGINT;
ALTER TABLE race_characteristic_modifiers ADD COLUMN tenant_id BIGINT;
ALTER TABLE race_special_abilities ADD COLUMN tenant_id BIGINT;
ALTER TABLE race_typical_homeworlds ADD COLUMN tenant_id BIGINT;
ALTER TABLE characteristics ADD COLUMN tenant_id BIGINT;
ALTER TABLE skills ADD COLUMN tenant_id BIGINT;
ALTER TABLE homeworlds ADD COLUMN tenant_id BIGINT;
ALTER TABLE homeworld_trade_codes ADD COLUMN tenant_id BIGINT;
ALTER TABLE homeworld_common_skills ADD COLUMN tenant_id BIGINT;
ALTER TABLE careers ADD COLUMN tenant_id BIGINT;
ALTER TABLE career_qualification_requirements ADD COLUMN tenant_id BIGINT;
ALTER TABLE career_basic_training_skills ADD COLUMN tenant_id BIGINT;
ALTER TABLE skill_tables ADD COLUMN tenant_id BIGINT;
ALTER TABLE ranks ADD COLUMN tenant_id BIGINT;
ALTER TABLE benefit_tables ADD COLUMN tenant_id BIGINT;
ALTER TABLE career_terms ADD COLUMN tenant_id BIGINT;
ALTER TABLE career_term_skills ADD COLUMN tenant_id BIGINT;
ALTER TABLE career_term_benefits ADD COLUMN tenant_id BIGINT;
ALTER TABLE weapons ADD COLUMN tenant_id BIGINT;
ALTER TABLE armor ADD COLUMN tenant_id BIGINT;
ALTER TABLE characters ADD COLUMN tenant_id BIGINT;
ALTER TABLE character_skills ADD COLUMN tenant_id BIGINT;
ALTER TABLE character_weapons ADD COLUMN tenant_id BIGINT;
ALTER TABLE character_armor ADD COLUMN tenant_id BIGINT;
ALTER TABLE equipment ADD COLUMN tenant_id BIGINT;
ALTER TABLE equipment_features ADD COLUMN tenant_id BIGINT;
ALTER TABLE political_entities ADD COLUMN tenant_id BIGINT;
ALTER TABLE subsectors ADD COLUMN tenant_id BIGINT;
ALTER TABLE sectors ADD COLUMN tenant_id BIGINT;
ALTER TABLE worlds ADD COLUMN tenant_id BIGINT;
ALTER TABLE world_trade_codes ADD COLUMN tenant_id BIGINT;
ALTER TABLE world_bases ADD COLUMN tenant_id BIGINT;
ALTER TABLE world_points_of_interest ADD COLUMN tenant_id BIGINT;
ALTER TABLE vehicles ADD COLUMN tenant_id BIGINT;
ALTER TABLE vehicle_features ADD COLUMN tenant_id BIGINT;
ALTER TABLE vehicle_weapons ADD COLUMN tenant_id BIGINT;
ALTER TABLE animals ADD COLUMN tenant_id BIGINT;
ALTER TABLE animal_attacks ADD COLUMN tenant_id BIGINT;
ALTER TABLE animal_special_traits ADD COLUMN tenant_id BIGINT;
ALTER TABLE spaceships ADD COLUMN tenant_id BIGINT;
ALTER TABLE spaceship_features ADD COLUMN tenant_id BIGINT;
ALTER TABLE spaceship_weapons ADD COLUMN tenant_id BIGINT;

-- Set all existing data to the default tenant
UPDATE races SET tenant_id = 1;
UPDATE race_characteristic_modifiers SET tenant_id = 1;
UPDATE race_special_abilities SET tenant_id = 1;
UPDATE race_typical_homeworlds SET tenant_id = 1;
UPDATE characteristics SET tenant_id = 1;
UPDATE skills SET tenant_id = 1;
UPDATE homeworlds SET tenant_id = 1;
UPDATE homeworld_trade_codes SET tenant_id = 1;
UPDATE homeworld_common_skills SET tenant_id = 1;
UPDATE careers SET tenant_id = 1;
UPDATE career_qualification_requirements SET tenant_id = 1;
UPDATE career_basic_training_skills SET tenant_id = 1;
UPDATE skill_tables SET tenant_id = 1;
UPDATE ranks SET tenant_id = 1;
UPDATE benefit_tables SET tenant_id = 1;
UPDATE career_terms SET tenant_id = 1;
UPDATE career_term_skills SET tenant_id = 1;
UPDATE career_term_benefits SET tenant_id = 1;
UPDATE weapons SET tenant_id = 1;
UPDATE armor SET tenant_id = 1;
UPDATE characters SET tenant_id = 1;
UPDATE character_skills SET tenant_id = 1;
UPDATE character_weapons SET tenant_id = 1;
UPDATE character_armor SET tenant_id = 1;
UPDATE equipment SET tenant_id = 1;
UPDATE equipment_features SET tenant_id = 1;
UPDATE political_entities SET tenant_id = 1;
UPDATE subsectors SET tenant_id = 1;
UPDATE sectors SET tenant_id = 1;
UPDATE worlds SET tenant_id = 1;
UPDATE world_trade_codes SET tenant_id = 1;
UPDATE world_bases SET tenant_id = 1;
UPDATE world_points_of_interest SET tenant_id = 1;
UPDATE vehicles SET tenant_id = 1;
UPDATE vehicle_features SET tenant_id = 1;
UPDATE vehicle_weapons SET tenant_id = 1;
UPDATE animals SET tenant_id = 1;
UPDATE animal_attacks SET tenant_id = 1;
UPDATE animal_special_traits SET tenant_id = 1;
UPDATE spaceships SET tenant_id = 1;
UPDATE spaceship_features SET tenant_id = 1;
UPDATE spaceship_weapons SET tenant_id = 1;

-- Add foreign key constraints
ALTER TABLE races ADD CONSTRAINT fk_races_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE race_characteristic_modifiers ADD CONSTRAINT fk_race_characteristic_modifiers_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE race_special_abilities ADD CONSTRAINT fk_race_special_abilities_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE race_typical_homeworlds ADD CONSTRAINT fk_race_typical_homeworlds_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE characteristics ADD CONSTRAINT fk_characteristics_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE skills ADD CONSTRAINT fk_skills_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE homeworlds ADD CONSTRAINT fk_homeworlds_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE homeworld_trade_codes ADD CONSTRAINT fk_homeworld_trade_codes_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE homeworld_common_skills ADD CONSTRAINT fk_homeworld_common_skills_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE careers ADD CONSTRAINT fk_careers_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE career_qualification_requirements ADD CONSTRAINT fk_career_qualification_requirements_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE career_basic_training_skills ADD CONSTRAINT fk_career_basic_training_skills_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE skill_tables ADD CONSTRAINT fk_skill_tables_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE ranks ADD CONSTRAINT fk_ranks_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE benefit_tables ADD CONSTRAINT fk_benefit_tables_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE career_terms ADD CONSTRAINT fk_career_terms_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE career_term_skills ADD CONSTRAINT fk_career_term_skills_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE career_term_benefits ADD CONSTRAINT fk_career_term_benefits_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE weapons ADD CONSTRAINT fk_weapons_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE armor ADD CONSTRAINT fk_armor_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE characters ADD CONSTRAINT fk_characters_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE character_skills ADD CONSTRAINT fk_character_skills_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE character_weapons ADD CONSTRAINT fk_character_weapons_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE character_armor ADD CONSTRAINT fk_character_armor_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE equipment ADD CONSTRAINT fk_equipment_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE equipment_features ADD CONSTRAINT fk_equipment_features_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE political_entities ADD CONSTRAINT fk_political_entities_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE subsectors ADD CONSTRAINT fk_subsectors_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE sectors ADD CONSTRAINT fk_sectors_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE worlds ADD CONSTRAINT fk_worlds_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE world_trade_codes ADD CONSTRAINT fk_world_trade_codes_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE world_bases ADD CONSTRAINT fk_world_bases_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE world_points_of_interest ADD CONSTRAINT fk_world_points_of_interest_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE vehicles ADD CONSTRAINT fk_vehicles_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE vehicle_features ADD CONSTRAINT fk_vehicle_features_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE vehicle_weapons ADD CONSTRAINT fk_vehicle_weapons_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE animals ADD CONSTRAINT fk_animals_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE animal_attacks ADD CONSTRAINT fk_animal_attacks_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE animal_special_traits ADD CONSTRAINT fk_animal_special_traits_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE spaceships ADD CONSTRAINT fk_spaceships_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE spaceship_features ADD CONSTRAINT fk_spaceship_features_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE spaceship_weapons ADD CONSTRAINT fk_spaceship_weapons_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);

-- Make tenant_id NOT NULL
ALTER TABLE races ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE race_characteristic_modifiers ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE race_special_abilities ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE race_typical_homeworlds ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE characteristics ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE skills ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE homeworlds ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE homeworld_trade_codes ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE homeworld_common_skills ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE careers ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE career_qualification_requirements ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE career_basic_training_skills ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE skill_tables ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE ranks ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE benefit_tables ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE career_terms ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE career_term_skills ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE career_term_benefits ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE weapons ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE armor ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE characters ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE character_skills ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE character_weapons ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE character_armor ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE equipment ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE equipment_features ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE political_entities ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE subsectors ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE sectors ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE worlds ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE world_trade_codes ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE world_bases ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE world_points_of_interest ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE vehicles ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE vehicle_features ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE vehicle_weapons ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE animals ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE animal_attacks ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE animal_special_traits ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE spaceships ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE spaceship_features ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE spaceship_weapons ALTER COLUMN tenant_id SET NOT NULL;
